### PR TITLE
News Week Clone

### PR DESCRIPTION
**Pull request by okusarobert**
## The news week project
This PR Clones the newsweek.com responsive design using Bootstrap CSS responsive utility classes.

### CODE REVIEW

**Review by umairarshadbutt — CHANGES_REQUESTED** [review]
# Status: REQUIRED CHANGES :warning: :construction: 

Hi  @okusarobert and @marcelomaidden
Such a remarkable project you made :+1: ! Awesome README :100: !
We, however, do have a few changes to carry out before we proceed (see review comment).

##

 For this project, we have to make sure nothing is messed up. Kindly compare the screenshots below 👇 and work on the suggested changes.
- [ ] Add project screenshot in README file  ([screenshot](https://user-images.githubusercontent.com/29689273/96323514-d6071980-1036-11eb-8ee7-59edcc1233ad.png) from Pathwright)



### Navbar
- [x] Remove the hamburger from the clone
- [x] Move User icon and subscribe button on the right

|[Source Page](https://www.newsweek.com/)|[Clone Page](https://marcelomaidden.github.io/newsweek_clone/)|
|:---:|:---:|
|source-page|clone|


### IN THE MAGAZINE
- [x] Manage the space on other divs like the original webpage

|[Source Page](https://www.newsweek.com/)|[Clone Page](https://marcelomaidden.github.io/newsweek_clone/)|
|:---:|:---:|
|source-page|clone|


### Sections
- [x] Add borderline to specify the sections
- [x] Give a prominent color to the section headings

|[Source Page](https://www.newsweek.com/)|[Clone Page](https://marcelomaidden.github.io/newsweek_clone/)|
|:---:|:---:|
|source-page|clone|


### Subscribe
- [ ] The text should be overflow on images on medium and small screens

|[Source Page](https://www.newsweek.com/)|[Clone Page](https://marcelomaidden.github.io/newsweek_clone/)|
|:---:|:---:|
|source-page|clone|

### Footer
- [x] Edition should on the left side
- [x] Give a margin-top to the copyright like the original webpage

|[Source Page](https://www.newsweek.com/)|[Clone Page](https://marcelomaidden.github.io/newsweek_clone/)|
|:---:|:---:|
|source-page|clone|






##
- **When you have made the specified changes, please submit another code review. Thank you!**
##
**If you are stuck at any point or have any questions, let me know on slack at any time. I will be happy to help**
HAPPY CODING :computer:
**[Umair Arshad](https://umairarshad.me/)**
[Twitter](https://twitter.com/its_UmairArshad) | [LinkedIn](https://www.linkedin.com/in/umair-arshad-butt/) | [GitHub](https://github.com/umairarshadbutt)

**Review by teekaytech — CHANGES_REQUESTED** [review]
## Status: Changes Required :warning: :vertical_traffic_light: 

### Hello team :wave:

_You did well in making those changes highlighted by the previous TSE. As you know, this is a large project and it's possible that one change leads to another. Let's review some required changes as highlighted below:_

**[ REQUIRED CHANGES ]**

**At small screen sizes (<768px)
- [x] Some changes are required in the NEWSLETTER section.
- You seem to have added a background color to the container. This is not the case on the original page. Kindly remove it.
- Looking at the original page, the height of the `SUBSCRIBE` and the `NEWSLETTER` section are equal. This is not the case on your page.

Your clone page:


Original page:


- [x] The social media icons are aligned to the right-most part of the page.

Your clone page:


Original page:


- [x] There are some issues with your navbar when viewed on medium screen sizes (1023px)
- Kindly compare your navbar with the original page and make changes as necessary.
- You can decrease the font size, centralize each item, and the likes, just to make sure that your navbar is similar to what we have on the original page.

Your clone page:


Original page:



**Please make the required changes and submit another review request when you are done.**

* * *

**_You can reach out to me on Twitter (@ola_lere), Github(@teekaytech), or slack (@taofeekolalere )_**
__Happy Coding :smiley:__

**Review by teekaytech — CHANGES_REQUESTED** [review]
## Status: Changes Required :warning: :vertical_traffic_light: 

### Hello team :wave:

__I must say, you've done an amazing job so far. Please note that you are expected to be more precise and to make sure that your page looks exactly the same as the source page in this project. See below some changes you have to make.__

**[ REQUIRED CHANGES ]**

- [x] Great job fixing the navbar. But we still have a major difference between your own and the source page.
- Try to centralize each of the items on the navbar so that the spaces are equally distributed to the left and right sides of the items.
- Move your `LOGIN` link closer to the `SUBSCRIBE` button, especially on large screen sizes.
- Remove the border (black) line of the `SUBSCRIBE` button.

Source (original) page:


Your (clone) page:


- [x] Your page is having a horizontal scroll bar on medium and small screen sizes. This might be caused by padding or margin set on one of your containers. Kindly identify and fix the problem.

- [x] The `Footer` section is having vertical lines separating each of the items. These lines are hidden on small screen sizes and shown for medium and large screen sizes. Kindly implement this.

Source (original) page:


Your (clone) page:


**[ COMMENTS ]**
- This is a big project. Therefore, in most cases, some changes will lead to another.
- Do not feel bad about these changes. They're being raised to ensure that you have a professional project that you can proud of.

* * * 
**Please make the required changes and submit another review request when you are done.**

* * *

**_You can reach out to me on Twitter (@ola_lere), Github(@teekaytech), or slack (@taofeekolalere )_**
__Happy Coding :smiley:__

**Review by arslanbisharat — APPROVED** [review]
### Approved :smile:



Hello, 👋 



I have approved this project because this is almost done. But please have a look at the changes i requested you to make. **These changes are highly recommended**.  These changes will help you to make this project exactly like original one. 



                                        ### Large Screen



- [ ] **Optional** Your navbar looks alike original one but on original page, the navbar decreases, date and location with weather disappears and Newsweek logo take their place. If you can make the navbar look like the original one it would be really great. 



- [ ] **Optional**  In original page the links row at the top of page has bold text. Please make that bold so it looks the  clone of Newsweek page. 



- [ ] **Optional** In subscribe section

-  there is no padding present to the right side but at original page there is padding. Please work on it. 

- the text `In-depth Stories You Don't See Elsewhere About Topics You Want to Read!` should be close to the images to the left. 

- please add space between` In-depth Stories You Don't See Elsewhere About Topics You Want to Read!` and

` All Access + Weekly Delivery.

Choose A Membership That's Perfect for You!

` and `subscribe button`. 

By this the page will look like original one. 



- [ ] **Optional** In Newsletter section there is no padding present to the right side but at original page there is padding. Please work on it. 





                                   ### Medium Screen 



- [ ] **Optional** On medium screen the navbar items are not correctly aligned. 

- the Newsweek logo should have lower width than present in your clone. 

- Newsweek logo, login and subscribe button, and hamburger should start little lower than present in your website.  



- [ ] **Optional** In subscribe section

-  there is no padding present to the right side but at original page there is padding. Please work on it. 

- the text `In-depth Stories You Don't See Elsewhere About Topics You Want to Read!` should be close to the images to the left. 

- please add space between` In-depth Stories You Don't See Elsewhere About Topics You Want to Read!` and

` All Access + Weekly Delivery.

Choose A Membership That's Perfect for You!

` and `subscribe button`. 

- Please align subscribe button according to the text above. 



By this the page will look like original one. 



- [ ] **Optional** In Newsletter section 

- there is no padding present to the right side but at original page there is padding.

- `THE STARTING 5` should have more font-size and it should present a little above than it's present right now. 

- `See why nearly a quarter of a million subscribers begin their day with the Starting 5.` should present exactly in the center of the section. 

- Email input and Free Signup button should have more width. 

 Please work on it. 



                       ### Small Screen

- [ ] **Optional**  There is extra spacing present between Newsletter and Subscribe section. Please remove that. 

- [ ] **Optional**  There is extra spacing present between Newsletter and Footer section. Please remove that. 

- [ ] **Optional** The footer has more padding than the original one. This is making the footer looks bad. 

Please work on these. 

-----------------------------------------------------------------------------------------------------

**Please make these changes and submit the project.** 



_If you have any question please reach me out or have a 1:1 meeting with a Full-Time TSE for greater explanation._ 



**Regards,

Arslan Bisharat

slack: arslanbisharat**

**Pull request merged**
